### ISSUE TITLE
Support Pimcore 5

### ISSUE THREAD

**Issue by janwalther** [pimcore/composer-installer-plugin#5]
Are there already any plans to support Pimcore 5 with this plugin or will there be another way to install Pimcore 5 bundles via Composer?

**Comment by maff** [comment]
Pimcore 5 bundles to not need a special install path anymore as they can be used directly from `vendor/` (the only important thing is that the code can be autoloaded). As the `vendor/` directory isn't accessible through the webserver anymore, bundles can provide public assets in a `Resources/public` directory (see http://symfony.com/blog/new-in-symfony-2-6-smarter-assets-install-command).

For more details on bundles in Pimcore 5 see: 

* https://www.pimcore.org/docs/5.0.0/Extending_Pimcore/Bundle_Developers_Guide/index.html
* https://www.pimcore.org/docs/5.0.0/Extending_Pimcore/Bundle_Developers_Guide/Pimcore_Bundles.html
